# Generated by Django 5.2.7 on 2026-04-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_column='User', max_length=80, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('phone', models.CharField(blank=True, db_column='Phone', default='', max_length=40)),
                ('address', models.CharField(blank=True, db_column='Address', default='', max_length=255)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Veterinario', 'Veterinario'), ('Cliente', 'Cliente')], db_column='Rol', default='Administrador', max_length=20)),
                ('nombre', models.CharField(blank=True, default='', max_length=120)),
                ('especialidad', models.CharField(blank=True, default='', max_length=120)),
                ('license', models.CharField(blank=True, default='', max_length=80)),
                ('profile_picture', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('especie', models.CharField(max_length=80)),
                ('raza', models.CharField(blank=True, default='', max_length=120)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='home.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_numero', models.CharField(blank=True, default='', max_length=80)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(blank=True, default='', max_length=10)),
                ('propietario_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('propietario_responsable', models.BooleanField(default=False)),
                ('propietario_documento_tipo', models.CharField(blank=True, default='', max_length=20)),
                ('propietario_documento_numero', models.CharField(blank=True, default='', max_length=40)),
                ('propietario_direccion', models.CharField(blank=True, default='', max_length=255)),
                ('propietario_telefono_fijo', models.CharField(blank=True, default='', max_length=40)),
                ('propietario_telefono_celular', models.CharField(blank=True, default='', max_length=40)),
                ('propietario_email', models.EmailField(blank=True, default='', max_length=254)),
                ('paciente_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('paciente_especie', models.CharField(blank=True, default='', max_length=80)),
                ('paciente_raza', models.CharField(blank=True, default='', max_length=120)),
                ('paciente_sexo', models.CharField(blank=True, default='', max_length=20)),
                ('paciente_fecha_nacimiento', models.CharField(blank=True, default='', max_length=20)),
                ('paciente_peso', models.CharField(blank=True, default='', max_length=20)),
                ('paciente_color', models.CharField(blank=True, default='', max_length=80)),
                ('paciente_chip', models.CharField(blank=True, default='', max_length=80)),
                ('paciente_otras_identificaciones', models.CharField(blank=True, default='', max_length=255)),
                ('paciente_fin_zootecnico', models.CharField(blank=True, default='', max_length=120)),
                ('paciente_origen', models.CharField(blank=True, default='', max_length=120)),
                ('anamnesis_dieta', models.TextField(blank=True, default='')),
                ('anamnesis_enfermedades_previas', models.TextField(blank=True, default='')),
                ('anamnesis_esterilizado', models.CharField(blank=True, default='', max_length=20)),
                ('anamnesis_num_partos', models.CharField(blank=True, default='', max_length=20)),
                ('anamnesis_cirugias_previas', models.TextField(blank=True, default='')),
                ('examen_fisico', models.TextField(blank=True, default='')),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('tratamiento', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='home.paciente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_creadas', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
                ('duracion', models.IntegerField(default=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('fecha_observacion', models.DateTimeField(blank=True, null=True)),
                ('veterinario_observacion', models.CharField(blank=True, default='', max_length=120)),
                ('paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='home.paciente')),
                ('veterinario', models.ForeignKey(blank=True, db_column='id_veterinario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=120)),
                ('detalle', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
