# Generated by Django 5.2.7 on 2026-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_categoria_producto_receta_recetaitem_venta_ventaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente_chip',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente_color',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente_especie',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente_fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente_fin_zootecnico',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente_nombre',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente_origen',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente_otras_identificaciones',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente_peso',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente_raza',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente_sexo',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='propietario_direccion',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='propietario_documento_numero',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='propietario_documento_tipo',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='propietario_email',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='propietario_nombre',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='propietario_responsable',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='propietario_telefono_celular',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='propietario_telefono_fijo',
        ),
        migrations.AddField(
            model_name='paciente',
            name='owner_direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paciente',
            name='owner_documento',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='paciente',
            name='owner_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='paciente',
            name='owner_telefono',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='paciente',
            name='owner_tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('RUT', 'RUT'), ('PAS', 'Pasaporte')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
