# Generated by Django 5.2.7 on 2026-05-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_historiaclinica_paciente_chip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo',
            field=models.CharField(choices=[('Medica', 'Médica'), ('Peluqueria', 'Peluquería')], default='Medica', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ofrece_consulta_medica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ofrece_peluqueria',
            field=models.BooleanField(default=False),
        ),
    ]
