# Generated by Django 5.2.7 on 2026-05-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cita_tipo_usuario_ofrece_consulta_medica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra'), ('Desconocido', 'Desconocido')], default='Desconocido', max_length=20),
        ),
    ]
