# Generated by Django 5.2.7 on 2026-05-08 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_paciente_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('tipo_documento', models.CharField(blank=True, choices=[('Cedula', 'Cédula'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte'), ('CedulaExtranjeria', 'Cédula de extranjería'), ('TarjetaIdentidad', 'Tarjeta de identidad'), ('Otro', 'Otro documento')], default='', max_length=30)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=40)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('contacto_autorizado', models.CharField(blank=True, default='', max_length=200)),
                ('telefono_alternativo', models.CharField(blank=True, default='', max_length=40)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='alimento',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='codigo_chip',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='paciente',
            name='color',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_reproductivo',
            field=models.CharField(blank=True, choices=[('Entero', 'Entero'), ('Esterilizado', 'Esterilizado'), ('Castrado', 'Castrado'), ('Desconocido', 'Desconocido')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='talla',
            field=models.CharField(blank=True, choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande'), ('Gigante', 'Gigante')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='unidad_peso',
            field=models.CharField(default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='owner_tipo_documento',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.CreateModel(
            name='Desparasitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa'), ('Interna y externa', 'Interna y externa')], default='Interna', max_length=30)),
                ('dosis', models.CharField(blank=True, default='', max_length=80)),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desparasitaciones', to='home.paciente')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desparasitaciones_aplicadas', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='home.propietario'),
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('dosis', models.CharField(blank=True, default='', max_length=80)),
                ('lote', models.CharField(blank=True, default='', max_length=80)),
                ('proxima_dosis', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='home.paciente')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunas_aplicadas', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
