# Generated by Django 5.2.7 on 2026-05-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_propietario_paciente_alimento_paciente_codigo_chip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desparasitacion',
            name='ultima_desparasitacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='examen_fisico_especial',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='examen_fisico_general',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='interpretacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='motivo_consulta',
            field=models.CharField(blank=True, choices=[('Consulta general', 'Consulta general'), ('Vacunación', 'Vacunación'), ('Control', 'Control'), ('Urgencia', 'Urgencia'), ('Cirugía', 'Cirugía'), ('Desparasitación', 'Desparasitación'), ('Baño y peluquería', 'Baño y peluquería'), ('Examen de laboratorio', 'Examen de laboratorio'), ('Otro', 'Otro')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='objetivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='plan_diagnostico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='plan_terapeutico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='proximo_control',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='subjetivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recetaitem',
            name='cantidad',
            field=models.CharField(blank=True, default='1', max_length=40),
        ),
        migrations.AddField(
            model_name='recetaitem',
            name='posologia',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recetaitem',
            name='presentacion',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='laboratorio',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre_cirugia', models.CharField(max_length=200)),
                ('descripcion_quirurgica', models.TextField(blank=True, default='')),
                ('preanestesico', models.TextField(blank=True, default='')),
                ('anestesico', models.TextField(blank=True, default='')),
                ('otros_medicamentos', models.TextField(blank=True, default='')),
                ('tratamiento', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('complicaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='home.paciente')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias_realizadas', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ExamenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_examen', models.CharField(choices=[('Hemograma', 'Hemograma'), ('Bioquímica', 'Bioquímica sérica'), ('Urianálisis', 'Urianálisis'), ('Coproscópico', 'Coproscópico'), ('Citología', 'Citología'), ('Cultivo', 'Cultivo y antibiograma'), ('Radiografía', 'Radiografía'), ('Ecografía', 'Ecografía'), ('Otro', 'Otro')], default='Hemograma', max_length=40)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('resultado', models.TextField(blank=True, default='')),
                ('laboratorio', models.CharField(blank=True, default='', max_length=120)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_laboratorio', to='home.paciente')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_solicitados', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('evolucion', models.TextField(blank=True, default='')),
                ('proximo_control', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='home.paciente')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_realizados', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
