# Generated by Django 5.2.7 on 2026-05-08 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_desparasitacion_ultima_desparasitacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, default='', max_length=120)),
                ('nombre_documento', models.CharField(blank=True, default='', max_length=200)),
                ('requiere_firma', models.CharField(choices=[('Si', 'Si requiere'), ('No', 'No requiere')], default='No', max_length=3)),
                ('contenido', models.TextField(blank=True, default='')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='home.paciente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ImagenDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ayuda_diagnostica', models.CharField(choices=[('Radiografía', 'Radiografía'), ('Ecografía', 'Ecografía'), ('Tomografía', 'Tomografía'), ('Resonancia', 'Resonancia magnética'), ('Endoscopia', 'Endoscopia'), ('Otro', 'Otro')], max_length=40)),
                ('signos_clinicos', models.TextField(blank=True, default='')),
                ('diagnostico_presuntivo', models.TextField(blank=True, default='')),
                ('tipo_estudio', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='imagenes_diagnosticas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_diagnosticas', to='home.paciente')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_solicitadas', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_orden', models.CharField(choices=[('Laboratorio', 'Laboratorio'), ('Imagenología', 'Imagenología'), ('Medicamento', 'Medicamento'), ('Procedimiento', 'Procedimiento'), ('Otro', 'Otro')], max_length=40)),
                ('seleccion', models.CharField(blank=True, default='', max_length=200)),
                ('cantidad', models.IntegerField(default=1)),
                ('prioridad', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Urgente', 'Urgente'), ('Emergencia', 'Emergencia')], default='', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('motivo', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='home.paciente')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_emitidas', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Peluqueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('servicio', models.CharField(choices=[('Baño', 'Baño'), ('Corte de pelo', 'Corte de pelo'), ('Baño y corte', 'Baño y corte'), ('Corte de uñas', 'Corte de uñas'), ('Limpieza dental', 'Limpieza dental'), ('Deslanado', 'Deslanado'), ('Spa completo', 'Spa completo'), ('Otro', 'Otro')], max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peluquerias', to='home.paciente')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peluquerias_realizadas', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('veterinario_referido', models.CharField(blank=True, default='', max_length=200)),
                ('clinica_destino', models.CharField(blank=True, default='', max_length=200)),
                ('motivo', models.TextField(blank=True, default='')),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remisiones', to='home.paciente')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_emitidas', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
