# Generated by Django 5.2.7 on 2026-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_documento_imagendiagnostica_orden_peluqueria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Consulta general', 'Consulta general'), ('Consulta especializada', 'Consulta especializada'), ('Vacunación', 'Vacunación'), ('Control y seguimiento', 'Control y seguimiento'), ('Peluquería básica', 'Peluquería básica'), ('Peluquería completa', 'Peluquería completa'), ('Baño y corte', 'Baño y corte'), ('Cirugía menor', 'Cirugía menor'), ('Cirugía mayor', 'Cirugía mayor'), ('Urgencias', 'Urgencias'), ('Otro', 'Otro')], max_length=60, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
    ]
