# Generated by Django 5.2.7 on 2026-05-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tarifacita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='cirugias/'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='seguimientos/'),
        ),
    ]
