# Generated by Django 5.2.7 on 2026-05-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cirugia_adjunto_seguimiento_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenlaboratorio',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='examenes/'),
        ),
    ]
