# Generated by Django 5.2.7 on 2026-05-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_examen_adjunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cirugia', 'Cirugía'), ('examen', 'Examen de laboratorio'), ('seguimiento', 'Seguimiento'), ('consulta', 'Consulta'), ('orden', 'Orden'), ('remision', 'Remisión'), ('peluqueria', 'Peluquería'), ('imagen', 'Imagen diagnóstica'), ('documento', 'Documento')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('archivo', models.FileField(upload_to='adjuntos/%Y/%m/')),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
