# Generated by Django 5.2.7 on 2026-05-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_adjunto_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='factura_enviada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='factura_enviada_to',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
