# Generated by Django 5.2.7 on 2026-05-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_venta_factura_enviada_at_venta_factura_enviada_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifacita',
            name='tipo',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
