# Generated by Django 5.2.7 on 2026-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_tipo_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='duracion',
            field=models.IntegerField(default=1),
        ),
    ]
