# Generated by Django 5.2.7 on 2026-05-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_cita_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifacita',
            name='categoria',
            field=models.CharField(choices=[('Medica', 'Médica / Veterinaria'), ('Peluqueria', 'Peluquería')], default='Medica', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
