# Generated by Django 5.2.7 on 2026-05-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_tarifacita_categoria_alter_cita_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remision',
            name='veterinario_referido',
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='precio_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='duracion',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='examenlaboratorio',
            name='tipo_examen',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='imagendiagnostica',
            name='ayuda_diagnostica',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tipo_orden',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Veterinario', 'Veterinario'), ('Peluquero', 'Peluquero')], db_column='Rol', default='Administrador', max_length=20),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_factura', models.CharField(blank=True, default='', max_length=200)),
                ('numero_factura', models.CharField(blank=True, default='', max_length=80)),
                ('fecha_factura', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('pago_pendiente', models.BooleanField(default=False)),
                ('proveedor', models.CharField(blank=True, default='', max_length=200)),
                ('nit_proveedor', models.CharField(blank=True, default='', max_length=40)),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='facturas_inventario/')),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notas', models.TextField(blank=True, default='')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='home.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
