# Generated by Django 5.2.7 on 2026-05-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_remision_veterinario_referido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_porcentaje',
            field=models.IntegerField(default=0),
        ),
    ]
