# Generated by Django 5.2.7 on 2026-05-20 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_movimiento_tipo_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('precio_venta', 'Precio venta'), ('precio_compra', 'Precio compra'), ('descuento_activado', 'Descuento activado'), ('descuento_desactivado', 'Descuento desactivado')], max_length=30)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descuento_porcentaje', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='home.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
