# Generated by Django 5.2.7 on 2026-06-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_historial_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='archivo_factura',
            field=models.TextField(blank=True, null=True),
        ),
    ]
