# Generated by Django 5.2.7 on 2026-07-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_movimiento_archivo_factura_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modulos_acceso',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SuperAdministrador', 'SuperAdministrador'), ('Administrador', 'Administrador'), ('Veterinario', 'Veterinario'), ('Peluquero', 'Peluquero')], db_column='Rol', default='Administrador', max_length=20),
        ),
    ]
