# Generated by Django 5.2.7 on 2026-07-16 17:32

from django.db import migrations


def set_superadmin_role(apps, schema_editor):
    Usuario = apps.get_model('home', 'Usuario')
    # Buscar el usuario con el email del administrador principal
    u = Usuario.objects.filter(email='admin@local').first()
    if u:
        u.rol = 'SuperAdministrador'
        u.save(update_fields=['rol'])


def rollback_superadmin_role(apps, schema_editor):
    Usuario = apps.get_model('home', 'Usuario')
    u = Usuario.objects.filter(email='admin@local').first()
    if u:
        u.rol = 'Administrador'
        u.save(update_fields=['rol'])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_usuario_superadmin_y_modulos_acceso'),
    ]

    operations = [
        migrations.RunPython(set_superadmin_role, rollback_superadmin_role),
    ]
