# Generated by Django 5.2.7 on 2026-08-19 16:32

from django.db import migrations


def create_sandra_user(apps, schema_editor):
    Usuario = apps.get_model('home', 'Usuario')
    # Create Sandra if she doesn't exist
    if not Usuario.objects.filter(user='sandra').exists() and not Usuario.objects.filter(email='sandra@local').exists():
        Usuario.objects.create(
            user='sandra',
            email='sandra@local',
            password='SandraAgropet2026!',
            rol='SuperAdministrador',
            nombre='Sandra',
            ofrece_consulta_medica=True,
            ofrece_peluqueria=True,
        )


def delete_sandra_user(apps, schema_editor):
    Usuario = apps.get_model('home', 'Usuario')
    Usuario.objects.filter(user='sandra').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_set_superadmin_role_for_admin_email'),
    ]

    operations = [
        migrations.RunPython(create_sandra_user, delete_sandra_user),
    ]
